package com.mgl.base;

public enum SpriteType {

	TERRAIN, PLAYER, OBJETIVE, POOP, DECORATIVE, POOP_BAR, INVISIBLE, ROCK, POWER, FOOD, WALL, FIRE, TRUNK, FINGER, SMASH, OBSTACLE, HEDGEHOG, GEL, SMASHER, PLATFORM, FLOOR, TUNNEL, LAKE, PLATFORM_MOBILE, ENEMY, METEOR, FINISH_POINT, BEGIN_POINT, ADN, CHECKPOINT, SHOT, VULCANO, VULCANO_BURBLE, PLAYER_DIED, STAR, PLAYER_COLLITION, WIN_PLAYER, LIKE_COIN, COLLITION_RPG, TREE, PORTAL, NPC, BUTTON_GENERAL, ITEM, DOOR_ACTIVATOR, DOOR, KEY, LEVER, VICTORY, DIALOG

}
