package com.mgl.base;

public enum SpriteType {

	TERRAIN, PLAYER, OBJETIVE, POOP, DECORATIVE, POOP_BAR, INVISIBLE, ROCK, POWER, FOOD, WALL, FIRE, TRUNK, FINGER, SMASH, OBSTACLE, HEDGEHOG, GEL, SMASHER, PLATFORM, FLOOR, TUNNEL, LAKE, PLATFORM_MOBILE, ENEMY, METEOR, FINISH_POINT,BEGIN_POINT, ADN, CHECKPOINT, SHOT, VULCANO, VULCANO_BURBLE, PLAYER_DIED, STAR, ICE_CUBE,BUTTON_GENERAL

}
