package com.mgl.base;

public enum StatusType {

	NORMAL, POOPED, WAITING, PLAYING, FALLING, POOP_GROUND, POOP_EXPLODING, FINISHED, POOP_FLYING, POOPED_END, SHOOTING, HITED_BY_ROCK, SHOWING_UMBRELLA, TWERKING, DESTROY_OVNI, TOUCHED, DIGING, DESAPEARING, APPEARING, JUMP_LONG, SHIP;
	
}
